# Generated by Django 5.0.1 on 2024-01-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Option',
            new_name='Choice',
        ),
    ]
